spring:
  application:
    name: scw-project
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowfunding?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name:  com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

server:
  port: 8000
eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
  client:
    service-url:
      defailtZone: http://localhost:8761/eureka/
      type: com.alibaba.druid.pool.DruidDataSource
feign:
  hystrix:
    enabled: true

#配置mybaits全局文件和mapper映射文件的路径
mybatis:
  config-location: classpath:mybaits/mybatis-config.xml
  mapper-locations: classpath:mybaits/mapper/*.xml


